### PR TITLE
Beta Merging (1)

### PR DESCRIPTION
**Pull request by jsonnet**
All the things

### CODE REVIEW

**Review by Lukas0815 — APPROVED** [review]

**Review by Lukas0815 — APPROVED** [review]

**Comment by Lukas0815** [comment]
hi

**Review by jsonnet — COMMENTED** [review]
OK

**Review by Lukas0815 — APPROVED** [review]
Yes, I know but I didn´t knew if I wanted to implement your settingsfile 
--> needs explanation since I want to work on the websitesettings next :D

**Comment by jsonnet** [comment]
Watch out I may have done something stupid, backup .gcc-flags.json before git-ignore gets back to action after updating from repo

**Comment by jsonnet** [comment]
Don't press delete :P

**Pull request merged**
